### ISSUE TITLE
Has the API endpoint changed?

### ISSUE THREAD

**Issue by bergutman** [depop/popget#9]
Hey there,
I was sort of stumbling around your codebase for fun and found this repository. Are you still actively maintaining popget? http://things.depop.com seems to point nowhere currently.
Thanks,
Connor Gutman

**Comment by anentropic** [comment]
yes we're maintaining and actively using popget

http://things.depop.com is not a thing. not sure what your question is?

**Comment by anentropic** [comment]
Oh sorry, that's just a made up example url in the docs

Popget is not intended as a _Depop API_ client, as Depop does not have a public API.

It's for building API clients for any API

**Comment by bergutman** [comment]
No worries! As a developer, it would be really cool to have a public API some day. I can only imagine what fun things people would build with it. Thanks for the timely response and keep up the great work!
Best,
Connor Gutman

**Comment by grcode123** [comment]
Eh, 2025, I wish you guys had a public API for at least a few endpoints, like publishing,updating, searching, and deleting listings
